import { defineResource } from "../_shared/define-resource.js";

const URI = "comet://bridge/overview";

const content = [
  "# Comet MCP Bridge",
  "",
  "Streamable-HTTP MCP server that gives any MCP client full remote control of",
  "Perplexity's Comet browser via CDP. Per-task isolation: each parallel",
  "workflow gets its own tab, CDP socket, and AI state — concurrent tasks",
  "cannot stomp on each other.",
  "",
  "## Quick start",
  "",
  "```text",
  "1. comet_status               → confirm the bridge can reach Comet",
  "2. comet_connect              → opens a Perplexity tab, returns task_id",
  "3. comet_ask task_id=… …      → send a prompt; parallel-safe across task_ids",
  "4. comet_task_close task_id=… → optional cleanup for kept-open tasks",
  "```",
  "",
  "`comet_ask` auto-closes completed one-shot task tabs by default. Pass",
  "`closeAfter=false` to keep a tab open for follow-up prompts or inspection,",
  "or `closeTimeout` to leave a short inspection window before auto-close.",
  "`comet_ask` returns completed answers directly. If a run outlives the",
  "tool-call window, it returns a structured async handoff with `task_id`,",
  "`next.poll`, `next.partial`, and `next.result`; a background watcher keeps",
  "reading status, stores the final result, and applies the same close",
  "preference. `wait=false` uses this async path immediately.",
  "",
  "## Reading responses (the one thing agents must get right)",
  "",
  "Every prompt-related tool (`comet_ask`, `comet_poll`, `comet_get_response`,",
  "`comet_results`) returns BOTH a text content block and a `structuredContent`",
  "object. Use the structured fields to decide what to do next:",
  "",
  "```text",
  "structuredContent: {",
  "  task_id, label?, keep_alive, auto_close_on_completion,",
  "  status: \"completed\" | \"working\" | \"input_required\" | \"failed\" | \"idle\",",
  "  completed: true | false,",
  "  result_delivery: \"direct\" | \"async\",",
  "  response?:         \"…final answer…\",       // present iff completed:true",
  "  partial_response?: \"…incomplete stream…\",  // present while still working",
  "  error?:            \"…\",                    // present iff status:\"failed\"",
  "  next: { poll, partial, result, stop }       // pointers, NOT a required step",
  "}",
  "```",
  "",
  "Decision rule:",
  "- `completed:true` + `result_delivery:\"direct\"` → DONE. Read `response`",
  "  (or the text block) and present it. Do NOT call `next.*` — those are just",
  "  convenience pointers for follow-up turns, not a required step.",
  "- `result_delivery:\"async\"` → not finished. Either call `comet_poll` until",
  "  `completed:true`, or wait and call `comet_results task_id=…` later. The",
  "  `partial_response` field is incomplete — never present it as final.",
  "- `status:\"input_required\"` → Comet is paused on a confirmation prompt.",
  "  Either call `comet_accept_banner` (safe confirmations only) or have the",
  "  user approve manually, then poll again.",
  "- `status:\"failed\"` → read `error`; do not retry blindly.",
  "",
  "## Mental model",
  "",
  "- A **task** = one Perplexity tab + one CDP socket + one ongoing chat conversation.",
  "- Created on demand by `comet_ask` (you usually do NOT need to call",
  "  `comet_connect` first), listed by `comet_tasks`, renamed by",
  "  `comet_rename_task`, killed by `comet_task_close`.",
  "- Every task-scoped tool takes an optional `task_id`. With one task active",
  "  it can be omitted; with 2+ active the call errors loudly so you cannot",
  "  cross-wire workflows.",
  "- Same `task_id` → calls serialize on a per-task lock and continue the same",
  "  Perplexity chat history. Different `task_id`s → true parallel, isolated",
  "  conversations.",
  "",
  "## Tab lifecycle (read this — it answers \"do I close the tab?\")",
  "",
  "- **One-shot question** (default `comet_ask`): the tab + task auto-close",
  "  as soon as the answer is captured. Don't call `comet_task_close` — there's",
  "  nothing left to close. The next `comet_ask` opens a fresh tab.",
  "- **Multi-turn conversation** in the same tab: pass `closeAfter:false` and",
  "  reuse the SAME `task_id` for every follow-up. Perplexity's chat history",
  "  is preserved between turns. When done, call `comet_task_close task_id=…`.",
  "- **Fresh chat in an existing task**: pass `newChat:true` to navigate that",
  "  task's tab back to perplexity.ai/ before sending the next prompt.",
  "- **Inspection window**: pass `closeTimeout:5000` to keep the tab open for",
  "  a few seconds after completion so `comet_screenshot` / `comet_html` /",
  "  `comet_console` can run before auto-close.",
  "- The tab is NEVER auto-closed while Comet is still working or awaiting",
  "  confirmation, regardless of `closeAfter`.",
  "",
  "## Prompting Comet (agentic vs. Q&A)",
  "",
  "Comet only switches into agent/browser mode when the prompt tells it to",
  "use the browser. Phrase prompts accordingly:",
  "",
  "- **Pure Q&A** — write the question normally:",
  "  `\"What is the capital of Iceland?\"`",
  "- **Agentic / browsing tasks** — write an INSTRUCTION, not a keyword query:",
  "  `\"Use your browser to navigate to https://news.ycombinator.com and tell me the top 5 story titles.\"`",
  "  `\"Open github.com/anthropics/anthropic-sdk-python, go to the Issues tab, and list the 3 oldest open issues.\"`",
  "  `\"Browse to my Gmail inbox and summarize the unread emails from today.\"`",
  "",
  "Avoid bare keyword prompts (`\"top 5 HN stories\"`) for browsing tasks —",
  "Comet may answer from cached knowledge instead of actually opening the page.",
  "The bridge auto-rewrites obvious URL/website prompts into agentic form,",
  "but explicit instructions are always more reliable.",
  "",
  "## The 33 tools at a glance",
  "",
  "**Lifecycle**",
  "- `comet_status` — bridge health + active task list",
  "- `comet_connect` — create a task; returns `task_id`. Args: `label?`, `keepAlive?`",
  "- `comet_tasks` — list active tasks (id, label, tab, url, age, idle, keepAlive)",
  "- `comet_task_close` — close one task or `all=true`",
  "- `comet_rename_task` — change a task's `label`",
  "- `comet_inspect` — URL/title/readyState/age/idle for a task",
  "",
  "**Driving Perplexity**",
  "- `comet_ask` — send a prompt, wait for the answer. Args: `newChat`,",
  "  `closeAfter`, `closeTimeout`, `context`, `timeout`. Completed tasks",
  "  auto-close unless `closeAfter=false` is passed.",
  "- `comet_poll` — non-blocking status; returns the response when ready",
  "- `comet_get_response` — peek at the latest visible response without waiting",
  "- `comet_results` — read retained results after async completion or tab close",
  "- `comet_result_delete` — delete retained result records early",
  "- `comet_stop` — interrupt the agent",
  "- `comet_mode` — switch search/research/labs/learn",
  "- `comet_accept_banner` — manual click of the 'Allow browser control' banner",
  "",
  "**Tab navigation & inspection**",
  "- `comet_navigate` / `comet_back` / `comet_forward` / `comet_reload`",
  "- `comet_screenshot` (viewport) / `comet_full_screenshot` (full page) / `comet_pdf`",
  "- `comet_html` — outerHTML of doc or selector match",
  "- `comet_dom_query` — querySelectorAll → array of {tag,id,class,attrs,text,visible}",
  "",
  "**Interaction (no agent)**",
  "- `comet_click` — click a CSS selector",
  "- `comet_type` — `Input.insertText`, optionally focusing a selector first",
  "- `comet_eval` — arbitrary async JS. **Disabled by default**",
  "  (`COMET_ENABLE_EVAL=true` to enable; XSS-equivalent inside the tab).",
  "",
  "**Debugging the page**",
  "- `comet_console` — buffered console entries",
  "- `comet_network` — buffered HTTP requests",
  "",
  "**Browser state**",
  "- `comet_cookies` / `comet_set_cookie`",
  "- `comet_set_viewport` — `Emulation.setDeviceMetricsOverride`",
  "- `comet_block_urls` — `Network.setBlockedURLs`",
  "- `comet_clear_cache` — browser-wide",
  "",
  "## Idle TTL & keep-alive",
  "",
  "Tasks idle for `COMET_TASK_IDLE_TTL_MS` (default 30 min) are auto-closed",
  "by a sweeper running every `COMET_TASK_IDLE_SWEEP_MS` (default 60s). The",
  "idle clock resets on every tool call. Pass `keepAlive=true` on",
  "`comet_connect` to opt out. Console/network buffers are capped at",
  "`COMET_MAX_CONSOLE` / `COMET_MAX_NETWORK` (default 500 each).",
  "Comet answer streams are tracked as fetch-backed SSE requests; tune",
  "`COMET_MAX_STREAM_REQUESTS` and `COMET_MAX_STREAM_TEXT` if needed.",
  "Final task outputs are retained with `COMET_RESULT_TTL_MS` and",
  "`COMET_RESULT_MAX_TEXT`; when Redis is configured they live in DB 4.",
  "",
  "## Connecting to Comet",
  "",
  "The bridge does not spawn Comet — it speaks CDP to a Comet already",
  "running with `--remote-debugging-port=9222`, reached via `COMET_CDP_URL`",
  "(default `http://host.docker.internal:9222`). Comet stores Perplexity",
  "login in its profile; use `comet_set_cookie` to seed auth state.",
  "",
  "## Read next",
  "",
  "- `comet://bridge/hosting-guide` — running Comet so this server can reach it.",
  "- `comet://bridge/recipes` — copy-pasteable workflows.",
].join("\n");

const resource = defineResource({
  uri: URI,
  name: "comet_bridge_overview",
  title: "Comet MCP Bridge — Overview & Tool Map",
  description:
    "Start here. Mental model, the 33 tools by category, parallelism, idle TTL, " +
    "and links to hosting + recipes.",
  mimeType: "text/markdown",
  annotations: {
    audience: ["assistant", "user"],
    priority: 0.9,
  },
  async read() {
    return {
      contents: [{ uri: URI, mimeType: "text/markdown", text: content }],
    };
  },
});

export default resource;
