import { defineResource } from "../_shared/define-resource.js";

const URI = "comet://bridge/hosting-guide";

const content = [
  "# Hosting the Comet MCP bridge",
  "",
  "## TL;DR",
  "",
  "The container does **not** run Comet. It only speaks CDP to a Comet that",
  "already exists somewhere reachable. Comet is macOS/Windows only — there is",
  "no Linux build, so a fully cloud-native deploy isn't possible. You run",
  "Comet on a workstation and the bridge talks to it.",
  "",
  "What you have to provide:",
  "",
  "1. A running Comet instance with `--remote-debugging-port=9222`.",
  "2. Network reachability from the container to that port.",
  "3. A logged-in Perplexity session inside that Comet (the bridge never",
  "   sees credentials — login persists in the browser profile).",
  "",
  "The CDP endpoint has no authentication; treat 9222 like SSH access to the",
  "browser and never expose it publicly.",
  "",
  "## Local development on a workstation",
  "",
  "1. Start Comet with `--remote-debugging-port=9222`.",
  "2. Run the bridge: `docker compose up -d` (or `npm run dev`, or",
  "   `docker compose -f docker-compose.dev.yml up` for an auth-disabled stack).",
  "3. The default `COMET_CDP_URL=http://host.docker.internal:9222` resolves to",
  "   the host on Docker Desktop (macOS/Windows).",
  "4. Log into Perplexity once in Comet — it persists in the profile.",
  "",
  "## Verifying the bridge",
  "",
  "Call `comet_status`. A healthy response includes the browser version,",
  "active task list, and any other tabs visible to the CDP endpoint. If",
  "`Browser: UNREACHABLE` appears, see the env knobs below.",
  "",
  "## Remote / cloud deployment",
  "",
  "Comet is desktop-only (macOS/Windows). There is no Linux build, so the",
  "browser cannot live in a Linux container or VM. The realistic path is to",
  "host the bridge anywhere and tunnel back to a Comet running on a",
  "workstation:",
  "",
  "- Comet runs on a Mac/Windows machine you control.",
  "- Tunnel port 9222 from that machine to the bridge host (Tailscale,",
  "  Cloudflare Tunnel, SSH `-R`).",
  "- Set `COMET_CDP_URL` on the bridge to the tunnel target.",
  "- Profile + login live on the workstation.",
  "",
  "Per-user variant: each user runs Comet locally and points a hosted bridge",
  "at it via tunnel. Best for multi-tenant; worst for ops.",
  "",
  "## Production checklist",
  "",
  "- **CDP port** has no auth — bind to localhost and tunnel; never expose 9222.",
  "- **MCP port** — keep `AUTH_MODE=bearer` and rotate `API_KEY`.",
  "- **Login persistence** — let Comet keep its default profile, or pin one",
  "  with `--user-data-dir=/path/to/profile`.",
  "- **Eval** — leave `COMET_ENABLE_EVAL=false` unless you trust every MCP",
  "  client that can reach the endpoint (XSS-equivalent inside the tab).",
  "- **Logging** — `LOG_FORMAT=json` for log aggregators; `LOG_REDACT=true`",
  "  (default) scrubs cookies/tokens.",
  "",
  "## Configuration (env vars)",
  "",
  "**Server**",
  "- `PORT` — HTTP listen port (default 3000).",
  "- `PUBLIC_BASE_URL` — used for OAuth metadata.",
  "- `SERVER_NAME` — name advertised in MCP `initialize` (default `comet-mcpgw`).",
  "",
  "**Auth on the MCP endpoint**",
  "- `AUTH_MODE` — `bearer` (default, uses `API_KEY`) or `none`.",
  "- `API_KEY` — bearer token clients must present.",
  "- `DISABLE_AUTH` — `true` forces `AUTH_MODE=none` (local dev only).",
  "- `MCP_ALLOWED_ORIGINS` — comma-separated origins permitted to call `/mcp`.",
  "",
  "**CDP**",
  "- `COMET_CDP_URL` — Comet debug endpoint (default",
  "  `http://host.docker.internal:9222`). Use the LAN IP / Tailscale name /",
  "  tunnel target when Comet is on another box.",
  "",
  "**Logging**",
  "- `LOG_LEVEL` — `debug` | `info` | `warn` | `error` | `silent` (default `info`).",
  "- `LOG_FORMAT` — `pretty` (default) or `json`.",
  "- `LOG_REDACT` — `true` (default) auto-scrubs `token`/`cookie`/`authorization`/etc.",
  "- `LOGGING_MODE` (legacy) — `standard` (default); `none` drops non-",
  "  `privacySafe` field bodies.",
  "",
  "**Sessions, rate-limit, Redis**",
  "- `SESSION_TTL_MS` — MCP session inactivity timeout (default 1 800 000 = 30 min).",
  "- `REDIS_URL` — optional Redis for sessions / rate-limit / tasks / tool cache.",
  "- `RATE_LIMIT_WINDOW_MS` — default rate-limit window (default 60 000).",
  "- `RATE_LIMIT_CLIENT_ID_HEADER` — per-client rate-limit header",
  "  (default `x-client-id`).",
  "",
  "**Comet task lifecycle**",
  "- `COMET_TASK_IDLE_TTL_MS` — auto-close idle tasks (default 1 800 000 = 30 min).",
  "  Per-task opt-out via `keepAlive=true` on `comet_connect`.",
  "- `COMET_TASK_IDLE_SWEEP_MS` — sweeper cadence (default 60 000).",
  "",
  "**Per-task buffers**",
  "- `COMET_MAX_CONSOLE` — console entries per task (default 500).",
  "- `COMET_MAX_NETWORK` — network entries per task (default 500).",
  "- `COMET_MAX_STREAM_REQUESTS` — fetch-backed SSE request entries per task",
  "  (default 100).",
  "- `COMET_MAX_STREAM_TEXT` — decoded SSE text retained per request",
  "  (default 250 000 chars).",
  "",
  "**Power tools**",
  "- `COMET_ENABLE_EVAL` — `true` to enable `comet_eval` (off by default).",
  "",
  "## Redis layout (when `REDIS_URL` is set)",
  "",
  "- DB 0 — MCP sessions",
  "- DB 1 — rate limiting",
  "- DB 2 — MCP tasks",
  "- DB 3 — tool cache",
  "",
  "## Diagnosing common failures",
  "",
  "| Symptom | Likely cause |",
  "|---|---|",
  "| `Browser: UNREACHABLE` from `comet_status` | Comet not running with `--remote-debugging-port`, or `COMET_CDP_URL` points to the wrong host |",
  "| `WebSocket connection closed` during `comet_connect` | Two `comet_connect` calls collided in an OLD singleton-based build — rebuild & restart |",
  "| `Cannot find input element` from `comet_ask` | Tab navigated away from Perplexity — `comet_navigate` back to `https://www.perplexity.ai/` |",
  "| `Prompt text not found in input` | Background-tab focus issue — the new build uses CDP `Input.insertText` to avoid this; rebuild if you still see it |",
  "| `comet_eval is disabled` | Restart server with `COMET_ENABLE_EVAL=true` |",
].join("\n");

const resource = defineResource({
  uri: URI,
  name: "comet_hosting_guide",
  title: "Comet Bridge — Hosting & Configuration",
  description:
    "How to run Comet so this server can reach it (Comet is macOS/Windows only), " +
    "every env var explained, production checklist, Redis layout, and a " +
    "diagnosing-common-failures table.",
  mimeType: "text/markdown",
  annotations: {
    audience: ["assistant", "user"],
    priority: 0.6,
  },
  async read() {
    return {
      contents: [{ uri: URI, mimeType: "text/markdown", text: content }],
    };
  },
});

export default resource;
