import { defineResource } from "../_shared/define-resource.js";

const URI = "comet://bridge/recipes";

const content = [
  "# Comet bridge — workflow recipes",
  "",
  "Copy-pasteable JSON-RPC `tools/call` patterns. Only `name` + `arguments` shown.",
  "",
  "## 0. Reading responses correctly (read this first)",
  "",
  "Every prompt-related tool (`comet_ask`, `comet_poll`, `comet_get_response`,",
  "`comet_results`) returns a `structuredContent` object alongside the text",
  "block. The shape:",
  "",
  "```jsonc",
  "{",
  "  \"task_id\": \"…\",",
  "  \"status\": \"completed\" | \"working\" | \"input_required\" | \"failed\" | \"idle\",",
  "  \"completed\": true,",
  "  \"result_delivery\": \"direct\",          // \"direct\" = answer is here, \"async\" = come back later",
  "  \"response\": \"…final answer…\",          // only present when completed:true",
  "  \"partial_response\": \"…incomplete…\",     // only while still working — NEVER present this as final",
  "  \"next\": { \"poll\": {...}, \"result\": {...} } // pointers, not required next steps",
  "}",
  "```",
  "",
  "Rule of thumb:",
  "- `completed:true` + `result_delivery:\"direct\"` → DONE. Read `response`.",
  "  Do NOT call `next.poll` or `next.result` — those are just hints for",
  "  follow-up turns.",
  "- `result_delivery:\"async\"` → not finished. Use `comet_poll` until",
  "  `completed:true`, or call `comet_results task_id=…` later for the",
  "  retained final answer.",
  "- `status:\"input_required\"` → Comet is paused on a confirmation. Call",
  "  `comet_accept_banner` (safe confirmations) or have the user approve.",
  "",
  "## 1. One-shot question (auto-cleanup)",
  "",
  "Easiest path — `comet_ask` auto-creates a task, runs the prompt, returns the",
  "answer, and auto-closes the tab. No `comet_connect`, no `comet_task_close`:",
  "",
  "```json",
  "{ \"name\": \"comet_ask\", \"arguments\": {",
  "  \"prompt\": \"What is the capital of Iceland?\"",
  "}}",
  "```",
  "",
  "## 1b. One-shot agentic / browsing task",
  "",
  "Phrase the prompt as an INSTRUCTION so Comet uses its browser:",
  "",
  "```json",
  "{ \"name\": \"comet_ask\", \"arguments\": {",
  "  \"prompt\": \"Use your browser to navigate to https://news.ycombinator.com and report the top 5 story titles with their points.\"",
  "}}",
  "```",
  "",
  "Bad version (Comet may answer from cached knowledge):",
  "",
  "```json",
  "{ \"name\": \"comet_ask\", \"arguments\": { \"prompt\": \"top 5 HN stories\" } }",
  "```",
  "",
  "## 2. Multi-turn conversation in the same tab",
  "",
  "Pattern: open with `comet_connect` (or just let `comet_ask` create the task),",
  "send every follow-up `comet_ask` with the SAME `task_id` AND `closeAfter:false`,",
  "then explicitly close at the end. The Perplexity chat history is preserved",
  "across turns; this is the equivalent of a real human chat thread.",
  "",
  "```json",
  "{ \"name\": \"comet_connect\", \"arguments\": { \"label\": \"thread\" } }",
  "{ \"name\": \"comet_ask\", \"arguments\": { \"task_id\": \"<id>\",",
  "  \"prompt\": \"Summarize the latest research on RLHF.\",",
  "  \"closeAfter\": false } }",
  "{ \"name\": \"comet_ask\", \"arguments\": { \"task_id\": \"<id>\",",
  "  \"prompt\": \"Now compare it to constitutional AI.\",",
  "  \"closeAfter\": false } }",
  "{ \"name\": \"comet_task_close\", \"arguments\": { \"task_id\": \"<id>\" } }",
  "```",
  "",
  "Forgetting `closeAfter:false` on a turn auto-closes the tab and ends the",
  "conversation. To start a fresh chat in the SAME task's tab without losing",
  "the task itself, pass `newChat:true` on the next `comet_ask`.",
  "",
  "## 3. Parallel tasks",
  "",
  "Different `task_id`s run in true parallel; same `task_id` queues on a per-task lock.",
  "",
  "```json",
  "{ \"name\": \"comet_connect\", \"arguments\": { \"label\": \"news\" } }",
  "{ \"name\": \"comet_connect\", \"arguments\": { \"label\": \"docs\" } }",
  "{ \"name\": \"comet_connect\", \"arguments\": { \"label\": \"deep\" } }",
  "",
  "{ \"name\": \"comet_ask\", \"arguments\": { \"task_id\": \"<news>\", \"prompt\": \"…\" } }",
  "{ \"name\": \"comet_ask\", \"arguments\": { \"task_id\": \"<docs>\", \"prompt\": \"…\" } }",
  "{ \"name\": \"comet_ask\", \"arguments\": { \"task_id\": \"<deep>\", \"mode\": \"research\", \"prompt\": \"…\" } }",
  "",
  "{ \"name\": \"comet_task_close\", \"arguments\": { \"all\": true } }",
  "```",
  "",
  "## 4. Long-running task with progress polling",
  "",
  "```json",
  "{ \"name\": \"comet_connect\", \"arguments\": { \"label\": \"deep\", \"keepAlive\": true } }",
  "{ \"name\": \"comet_mode\",    \"arguments\": { \"task_id\": \"<id>\", \"mode\": \"research\" } }",
  "{ \"name\": \"comet_ask\", \"arguments\": {",
  "  \"task_id\": \"<id>\",",
  "  \"prompt\": \"Compile the top 10 CDP-related changes in the last year.\",",
  "  \"timeout\": 60000",
  "}}",
  "{ \"name\": \"comet_poll\", \"arguments\": { \"task_id\": \"<id>\" } }",
  "```",
  "",
  "Repeat `comet_poll` until it returns the completed response.",
  "`comet_get_response` peeks at partial output; `comet_results` can retrieve",
  "the retained final result after auto-close; `comet_stop` cancels.",
  "",
  "## 5. Drive a page (no agent)",
  "",
  "```json",
  "{ \"name\": \"comet_navigate\",  \"arguments\": { \"task_id\": \"<t>\", \"url\": \"https://example.com\" } }",
  "{ \"name\": \"comet_dom_query\", \"arguments\": { \"task_id\": \"<t>\", \"selector\": \"a\", \"limit\": 10 } }",
  "{ \"name\": \"comet_click\",     \"arguments\": { \"task_id\": \"<t>\", \"selector\": \"a\" } }",
  "{ \"name\": \"comet_html\",      \"arguments\": { \"task_id\": \"<t>\", \"selector\": \"main\", \"maxBytes\": 50000 } }",
  "```",
  "",
  "## 6. Debug a flaky page",
  "",
  "```json",
  "{ \"name\": \"comet_console\",         \"arguments\": { \"task_id\": \"<t>\", \"level\": \"error\" } }",
  "{ \"name\": \"comet_network\",         \"arguments\": { \"task_id\": \"<t>\", \"onlyFailed\": true } }",
  "{ \"name\": \"comet_full_screenshot\", \"arguments\": { \"task_id\": \"<t>\" } }",
  "{ \"name\": \"comet_html\",            \"arguments\": { \"task_id\": \"<t>\", \"selector\": \"#root\" } }",
  "```",
  "",
  "## 7. Seed auth state",
  "",
  "```json",
  "{ \"name\": \"comet_set_cookie\", \"arguments\": {",
  "  \"task_id\": \"<t>\", \"name\": \"session\", \"value\": \"<token>\",",
  "  \"url\": \"https://www.perplexity.ai/\", \"httpOnly\": true, \"secure\": true",
  "}}",
  "{ \"name\": \"comet_navigate\", \"arguments\": { \"task_id\": \"<t>\", \"url\": \"https://www.perplexity.ai/\" } }",
  "```",
  "",
  "## 8. Mobile emulation",
  "",
  "```json",
  "{ \"name\": \"comet_set_viewport\", \"arguments\": {",
  "  \"task_id\": \"<t>\", \"width\": 390, \"height\": 844, \"deviceScaleFactor\": 3, \"mobile\": true",
  "}}",
  "```",
  "",
  "To restore the viewport, pass `width=0` and `height=0`.",
  "",
  "## 9. Block trackers",
  "",
  "```json",
  "{ \"name\": \"comet_block_urls\", \"arguments\": {",
  "  \"task_id\": \"<t>\",",
  "  \"patterns\": [ \"*://*.doubleclick.net/*\", \"*://*.google-analytics.com/*\", \"*://*.facebook.net/*\" ]",
  "}}",
  "```",
  "",
  "To clear the block list, pass an empty `patterns` array.",
  "",
  "## 10. Eval (when enabled)",
  "",
  "Server needs `COMET_ENABLE_EVAL=true`. Expression is wrapped in",
  "`(async () => (<expression>))()`, so `await` works.",
  "",
  "```json",
  "{ \"name\": \"comet_eval\", \"arguments\": {",
  "  \"task_id\": \"<t>\",",
  "  \"expression\": \"({ links: document.querySelectorAll('a').length, title: document.title })\"",
  "}}",
  "```",
  "",
  "## 11. Async retained result",
  "",
  "```json",
  "{ \"name\": \"comet_ask\", \"arguments\": {",
  "  \"prompt\": \"Use your browser to research the latest Node.js release notes.\",",
  "  \"wait\": false",
  "}}",
  "{ \"name\": \"comet_results\", \"arguments\": { \"task_id\": \"<id>\" } }",
  "{ \"name\": \"comet_result_delete\", \"arguments\": { \"task_id\": \"<id>\" } }",
  "```",
  "",
  "`wait=false` starts a background watcher immediately. With `wait=true`,",
  "`comet_ask` returns the final answer directly when ready; if the tool-call",
  "window expires first, it returns the same structured async handoff with",
  "`task_id`, `next.poll`, `next.partial`, and `next.result`. The final result",
  "is retained before auto-close, so workflow runners do not need a tight poll",
  "loop.",
  "",
  "## Pitfalls",
  "",
  "- Missing `task_id` with multiple tasks active → errors loudly listing all",
  "  active task_ids (intentional; silent defaults would cross-wire workflows).",
  "- Closing too eagerly → use `closeAfter=false` for follow-up work, or",
  "  `closeTimeout=…` so downstream tools have a window to inspect the tab.",
  "- Banner blocking the agent → `comet_ask` auto-accepts on a 1.5s loop;",
  "  fall back to `comet_accept_banner` if it sticks.",
].join("\n");

const resource = defineResource({
  uri: URI,
  name: "comet_recipes",
  title: "Comet Bridge — Workflow Recipes",
  description:
    "Copy-pasteable JSON-RPC examples for the 11 most common workflows: " +
    "one-shot, multi-step, parallel, polling, drive-a-page, debug, seed auth, " +
    "mobile emulation, block trackers, eval, retained async results.",
  mimeType: "text/markdown",
  annotations: {
    audience: ["assistant", "user"],
    priority: 0.85,
  },
  async read() {
    return {
      contents: [{ uri: URI, mimeType: "text/markdown", text: content }],
    };
  },
});

export default resource;
